-- This profile intentionally contains ASCII only. Keep it that way: it is the
-- rendering guarantee for terminals whose font capabilities are unknown.
return {
  name = "ascii",
  has_nerd_font = false,
  border = "none",
  diagnostic = {
    error = "E",
    warn = "W",
    info = "I",
    hint = "H",
  },
  telescope = {
    prompt = "> ",
    selection = "> ",
  },
  indent = "|",
  separator = "|",
  nvim_tree = {
    default = "",
    symlink = "@",
    bookmark = "B",
    modified = "M",
    hidden = ".",
    folder = {
      arrow_closed = ">",
      arrow_open = "v",
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "@",
      symlink_open = "@",
    },
    git = {
      unstaged = "M",
      staged = "S",
      unmerged = "U",
      renamed = "R",
      untracked = "?",
      deleted = "D",
      ignored = "I",
    },
  },
  bufferline = {
    file = "",
    close = "x",
  },
  lualine = {
    branch = "git:",
    added = "+",
    modified = "~",
    removed = "-",
  },
  aerial = {
    Collapsed = ">",
  },
  mason = {
    package_installed = "+",
    package_pending = ">",
    package_uninstalled = "-",
  },
  which_key = {
    breadcrumb = ">",
    separator = ">",
    ellipsis = "...",
  },
  lazy = {
    cmd = "$ ",
    config = "*",
    debug = "D ",
    event = "@ ",
    favorite = "* ",
    ft = "F ",
    init = "I ",
    import = "< ",
    keys = "K ",
    lazy = "L ",
    loaded = "+",
    not_loaded = "-",
    plugin = "P ",
    runtime = "R ",
    require = "Q ",
    source = "S ",
    start = "> ",
    task = "+ ",
    list = { "-", ">", "*", "=" },
  },
}
