-- This profile intentionally contains ASCII only. Keep it that way: it is the
-- rendering guarantee for terminals whose font capabilities are unknown.
return {
  name = "ascii",
  has_unicode = false,
  has_nerd_font = false,
  border = "none",
  diagnostic = {
    error = "E",
    warn = "W",
    info = "I",
    hint = "H",
  },
  telescope = {
    prompt = "> ",
    selection = "> ",
  },
  completion_kind = {},
  indent = "|",
  separator = "|",
  nvim_tree = {
    default = "",
    symlink = "@",
    bookmark = "B",
    modified = "M",
    hidden = ".",
    folder = {
      arrow_closed = ">",
      arrow_open = "v",
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "@",
      symlink_open = "@",
    },
    git = {
      unstaged = "M",
      staged = "S",
      unmerged = "U",
      renamed = "R",
      untracked = "?",
      deleted = "D",
      ignored = "I",
    },
  },
  bufferline = {
    file = "",
    close = "x",
    modified = "*",
    indicator = "|",
    left_trunc = "<",
    right_trunc = ">",
    pinned = "^",
    separator = { "", "" },
  },
  lualine = {
    branch = "git:",
    added = "+",
    modified = "~",
    removed = "-",
  },
  aerial = {
    Collapsed = ">",
  },
  mason = {
    package_installed = "+",
    package_pending = ">",
    package_uninstalled = "-",
  },
  noice = {
    cmdline = ":",
    search_down = "/",
    search_up = "?",
    filter = "$",
    lua = "lua",
    help = "?",
    calculator = "=",
    input = ">",
  },
  which_key = {
    breadcrumb = ">",
    separator = ">",
    ellipsis = "...",
    keys = {
      Up = "Up ",
      Down = "Down ",
      Left = "Left ",
      Right = "Right ",
      C = "C-",
      M = "M-",
      D = "D-",
      S = "S-",
      CR = "Enter ",
      Esc = "Esc ",
      ScrollWheelDown = "WheelDown ",
      ScrollWheelUp = "WheelUp ",
      NL = "Enter ",
      BS = "Backspace ",
      Space = "Space ",
      Tab = "Tab ",
      F1 = "F1",
      F2 = "F2",
      F3 = "F3",
      F4 = "F4",
      F5 = "F5",
      F6 = "F6",
      F7 = "F7",
      F8 = "F8",
      F9 = "F9",
      F10 = "F10",
      F11 = "F11",
      F12 = "F12",
    },
  },
  lazy = {
    cmd = "$ ",
    config = "*",
    debug = "D ",
    event = "@ ",
    favorite = "* ",
    ft = "F ",
    init = "I ",
    import = "< ",
    keys = "K ",
    lazy = "L ",
    loaded = "+",
    not_loaded = "-",
    plugin = "P ",
    runtime = "R ",
    require = "Q ",
    source = "S ",
    start = "> ",
    task = "+ ",
    list = { "-", ">", "*", "=" },
  },
}
