return {
  name = "nerd",
  has_nerd_font = true,
  border = "rounded",
  diagnostic = {
    error = "",
    warn = "",
    info = "",
    hint = "󰌵",
  },
  telescope = {
    prompt = " ",
    selection = " ",
  },
  indent = "│",
  separator = "│",
  nvim_tree = {
    default = "",
    symlink = "",
    bookmark = "󰆤",
    modified = "●",
    hidden = "󰜌",
    folder = {
      arrow_closed = "",
      arrow_open = "",
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "",
      symlink_open = "",
    },
    git = {
      unstaged = "✗",
      staged = "✓",
      unmerged = "",
      renamed = "➜",
      untracked = "★",
      deleted = "",
      ignored = "◌",
    },
  },
  bufferline = {
    close = "",
  },
  lualine = {
    branch = "",
    added = "",
    modified = "",
    removed = "",
  },
  aerial = {},
  mason = {
    package_installed = "◍",
    package_pending = "◍",
    package_uninstalled = "◍",
  },
  which_key = {
    breadcrumb = "»",
    separator = "➜",
    ellipsis = "…",
  },
  lazy = {
    cmd = " ",
    config = "",
    debug = "● ",
    event = " ",
    favorite = " ",
    ft = " ",
    init = " ",
    import = " ",
    keys = " ",
    lazy = "󰒲 ",
    loaded = "●",
    not_loaded = "○",
    plugin = " ",
    runtime = " ",
    require = "󰢱 ",
    source = " ",
    start = " ",
    task = "✔ ",
    list = { "●", "➜", "★", "‒" },
  },
}
