-- Nerd Font-only overrides. Common Unicode values come from unicode.lua and
-- every omitted value ultimately falls back to ascii.lua.
return {
  name = "nerd",
  has_nerd_font = true,
  diagnostic = {
    error = "",
    warn = "",
    info = "",
    hint = "󰌵",
  },
  telescope = {
    prompt = " ",
    selection = " ",
  },
  completion_kind = {
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "󰅲",
  },
  nvim_tree = {
    default = "",
    symlink = "",
    bookmark = "󰆤",
    hidden = "󰜌",
    folder = {
      arrow_closed = "",
      arrow_open = "",
      default = "",
      open = "",
      empty = "",
      empty_open = "",
      symlink = "",
      symlink_open = "",
    },
    git = {
      unmerged = "",
      deleted = "",
    },
  },
  bufferline = {
    close = "",
    left_trunc = "",
    right_trunc = "",
    pinned = "󰐃",
  },
  lualine = {
    branch = "",
    added = "",
    modified = "",
    removed = "",
  },
  noice = {
    cmdline = "",
    search_down = " ",
    search_up = " ",
    lua = "",
    help = "",
    calculator = "",
    input = "󰥻 ",
  },
  which_key = {
    keys = {
      Up = " ",
      Down = " ",
      Left = " ",
      Right = " ",
      C = "󰘴 ",
      M = "󰘵 ",
      D = "󰘳 ",
      S = "󰘶 ",
      CR = "󰌑 ",
      Esc = "󱊷 ",
      ScrollWheelDown = "󱕐 ",
      ScrollWheelUp = "󱕑 ",
      NL = "󰌑 ",
      BS = "󰁮",
      Space = "󱁐 ",
      Tab = "󰌒 ",
      F1 = "󱊫",
      F2 = "󱊬",
      F3 = "󱊭",
      F4 = "󱊮",
      F5 = "󱊯",
      F6 = "󱊰",
      F7 = "󱊱",
      F8 = "󱊲",
      F9 = "󱊳",
      F10 = "󱊴",
      F11 = "󱊵",
      F12 = "󱊶",
    },
  },
  lazy = {
    cmd = " ",
    config = "",
    event = " ",
    favorite = " ",
    ft = " ",
    init = " ",
    import = " ",
    keys = " ",
    lazy = "󰒲 ",
    plugin = " ",
    runtime = " ",
    require = "󰢱 ",
    source = " ",
    start = " ",
  },
}
