#!/bin/python
import os
import time
import psutil

def get_date():
    return time.ctime()

def get_battery_status():
    battery = psutil.sensors_battery()
    return (battery.percent, battery.power_plugged, battery.secsleft)
def refresh():
    while True:
        time_now = get_date()
        battery_status = get_battery_status()
        os.system("xsetroot -name '{} | {}'".format(time_now, battery_status[0]))
        time.sleep(2)

refresh()
